server:
  port: "8080"
  mode: "debug"  # debug, release

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "rootpassword"
  dbname: "ino"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

milvus:
  host: "localhost"
  port: 19530

neo4j:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "neo4jpassword"

indexer:
  embedding:
    base_url: "https://ark.cn-beijing.volces.com/api/v3"
    api_key: "b6582d68-9832-410b-ac22-acf3b60f50f2"
    model: "ep-20250714161406-8t29t"
  extractor:
    base_url: "https://ark.cn-beijing.volces.com/api/v3"
    api_key: "b6582d68-9832-410b-ac22-acf3b60f50f2"
    model: "ep-20250707170043-q9254"
  # embedding:
  #   base_url: "https://api.siliconflow.cn/v1/embeddings"
  #   api_key: "sk-voxftsvsnuopuqmerrudlhliotgqosanjiimipdeninzagrq"
  #   model: "BAAI/bge-m3"
  # extractor:
  #   base_url: "https://api.siliconflow.cn/v1/chat/completions"
  #   api_key: "sk-voxftsvsnuopuqmerrudlhliotgqosanjiimipdeninzagrq"
  #   model: "Qwen/Qwen3-8B" # THUDM/GLM-4-9B-0414
  

# 日志配置
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout"  # stdout, file

# 应用配置
app:
  name: "ino Knowledge System"
  version: "v1.0.0"
  debug: true

# 文件上传配置
upload:
  max_size: 104857600  # 100MB
  allowed_types: ["pdf", "txt", "md", "doc", "docx"]
  storage_path: "/app/uploads"

# 缓存配置
cache:
  default_ttl: 1800  # 30分钟
  max_keys: 10000 